# Set the build OS
dist: trusty

# Enable C++ support
language: cpp

# Enable build tests on all branches
branches:
  only:
    - /.*/

# Compiler selection
compiler:
  - gcc

# Build steps
script:
  - make -j
